const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const vscode = require('vscode');
const { BridgeCliBridge, BridgeCliError, renderPreviewHtml } = require('./lib/bridge_client');
function relPath(workspaceFolder, filePath) { return path.relative(workspaceFolder.uri.fsPath, filePath).replace(/\\/g, '/'); }
function decodeInputText(value) { return String(value || '').replace(/\n/g, '
'); }
class Item extends vscode.TreeItem { constructor(label, collapsibleState = vscode.TreeItemCollapsibleState.None) { super(label, collapsibleState); } }
class SearchResultsProvider { constructor(state) { this.state = state; this._emitter = new vscode.EventEmitter(); this.onDidChangeTreeData = this._emitter.event; } refresh() { this._emitter.fire(); } getTreeItem(element) { return element; } getChildren(element) { if (element) return []; return this.state.searchResults.map((match) => { const item = new Item(`${match.path}:${match.line_start} ${match.snippet}`); item.description = `${match.block_type} · ${match.confidence}`; item.tooltip = `${match.selector_reason}
${match.anchor || ''}`; item.command = { command: 'bridgeAi.openSearchResult', title: 'Open Search Result', arguments: [match] }; item.contextValue = 'bridge-search-result'; return item; }); } }
class SessionProvider { constructor(state) { this.state = state; this._emitter = new vscode.EventEmitter(); this.onDidChangeTreeData = this._emitter.event; } refresh() { this._emitter.fire(); } getTreeItem(element) { return element; } getChildren(element) { if (!this.state.sessionInspect) return []; if (!element) { return (this.state.sessionInspect.files || []).map((file) => { const item = new Item(file.path, vscode.TreeItemCollapsibleState.Expanded); item.description = `${file.change_count} changes · ${file.risk_level}`; item.tooltip = file.summary; item.contextValue = 'bridge-staged-file'; item.filePath = file.path; return item; }); } const file = this.state.sessionInspect.files.find((candidate) => candidate.path === element.filePath); if (!file) return []; return (this.state.sessionInspect.items || []).filter((item) => item.path === file.path).map((item) => { const child = new Item(`${item.operation} · lines ${item.line_start}-${item.line_end}`); child.description = item.risk_level; child.tooltip = `${item.selector_reason}
${item.anchor || ''}`; child.contextValue = 'bridge-staged-change'; child.changeId = item.change_id; child.filePath = item.path; return child; }); } }
async function getBridge(context) { const workspaceFolder = vscode.workspace.workspaceFolders?.[0]; if (!workspaceFolder) throw new Error('Open a workspace folder first.'); const config = vscode.workspace.getConfiguration('bridgeAi'); const cliPath = config.get('cliPath'); if (!cliPath) throw new Error('Set bridgeAi.cliPath first.'); const sessionId = context.workspaceState.get('bridgeAi.sessionId') || config.get('sessionId') || 'vscode-session'; return new BridgeCliBridge(cliPath, workspaceFolder.uri.fsPath, { sessionId, clientId: 'vscode-extension' }); }
async function withBridge(context, fn, output) { try { const bridge = await getBridge(context); return await fn(bridge); } catch (error) { const message = error instanceof BridgeCliError ? `${error.code}: ${error.message}` : String(error.message || error); output.appendLine(message); vscode.window.showErrorMessage(message); throw error; } }
function activate(context) { const output = vscode.window.createOutputChannel('AI Bridge'); const state = { searchResults: [], sessionInspect: null }; const searchProvider = new SearchResultsProvider(state); const sessionProvider = new SessionProvider(state); context.subscriptions.push(output, vscode.window.registerTreeDataProvider('bridgeAi.searchResults', searchProvider), vscode.window.registerTreeDataProvider('bridgeAi.stagedChanges', sessionProvider)); async function refreshSession() { const inspect = await withBridge(context, (bridge) => bridge.sessionInspect(), output); state.sessionInspect = inspect; sessionProvider.refresh(); if (inspect.risk_level && inspect.risk_level !== 'low') vscode.window.showWarningMessage(`AI Bridge session risk: ${inspect.risk_level}. ${inspect.summary}`); return inspect; }
context.subscriptions.push(vscode.commands.registerCommand('bridgeAi.configureCliPath', async () => { const current = vscode.workspace.getConfiguration('bridgeAi').get('cliPath', ''); const value = await vscode.window.showInputBox({ prompt: 'Path to bridge_cli binary', value: current }); if (!value) return; await vscode.workspace.getConfiguration('bridgeAi').update('cliPath', value, vscode.ConfigurationTarget.Workspace); }));
context.subscriptions.push(vscode.commands.registerCommand('bridgeAi.sessionBegin', async () => { const bridge = await getBridge(context); const result = await bridge.sessionBegin(); await context.workspaceState.update('bridgeAi.sessionId', result.session_id); output.appendLine(`session.begin -> ${result.session_id}`); await refreshSession(); }));
context.subscriptions.push(vscode.commands.registerCommand('bridgeAi.searchText', async () => { const editor = vscode.window.activeTextEditor; const defaultQuery = editor ? editor.document.getText(editor.selection) : ''; const query = await vscode.window.showInputBox({ prompt: 'Search query', value: defaultQuery }); if (!query) return; const result = await withBridge(context, (bridge) => bridge.searchText(query, { maxResults: 50 }), output); state.searchResults = (result.matches || []).map((match) => ({ ...match, searchQuery: query })); searchProvider.refresh(); vscode.window.showInformationMessage(`AI Bridge: ${state.searchResults.length} matches`); }));
context.subscriptions.push(vscode.commands.registerCommand('bridgeAi.openSearchResult', async (match) => { const workspaceFolder = vscode.workspace.workspaceFolders?.[0]; if (!workspaceFolder) return; const doc = await vscode.workspace.openTextDocument(vscode.Uri.file(path.join(workspaceFolder.uri.fsPath, match.path))); const editor = await vscode.window.showTextDocument(doc); const line = Math.max(0, Number(match.line_start || 1) - 1); const range = new vscode.Range(line, 0, line, 0); editor.selection = new vscode.Selection(range.start, range.end); editor.revealRange(range, vscode.TextEditorRevealType.InCenter); }));
context.subscriptions.push(vscode.commands.registerCommand('bridgeAi.stageReplaceFromSearch', async (match) => { const replacement = await vscode.window.showInputBox({ prompt: 'Replacement text (use \n for new lines)' }); if (replacement === undefined) return; const tempPath = path.join(os.tmpdir(), `bridge_vscode_${Date.now()}.txt`); fs.writeFileSync(tempPath, decodeInputText(replacement), 'utf8'); await withBridge(context, (bridge) => bridge.editReplaceBlock(match.path, match.searchQuery || match.snippet, tempPath, match.anchor), output); await refreshSession(); }));
context.subscriptions.push(vscode.commands.registerCommand('bridgeAi.stageReplaceSelection', async () => { const editor = vscode.window.activeTextEditor; const workspaceFolder = vscode.workspace.workspaceFolders?.[0]; if (!editor || !workspaceFolder) throw new Error('Open a file inside the workspace first.'); const replacement = await vscode.window.showInputBox({ prompt: 'Replacement text (use \n for new lines)' }); if (replacement === undefined) return; const startLine = editor.selection.start.line + 1; const endLine = editor.selection.end.line + 1; const tempPath = path.join(os.tmpdir(), `bridge_vscode_${Date.now()}.txt`); fs.writeFileSync(tempPath, decodeInputText(replacement), 'utf8'); await withBridge(context, (bridge) => bridge.editReplaceRange(relPath(workspaceFolder, editor.document.uri.fsPath), startLine, endLine, tempPath), output); await refreshSession(); }));
context.subscriptions.push(vscode.commands.registerCommand('bridgeAi.refreshSession', refreshSession));
context.subscriptions.push(vscode.commands.registerCommand('bridgeAi.previewSession', async () => { const preview = await withBridge(context, (bridge) => bridge.sessionPreview(), output); if (preview.risk_level && preview.risk_level !== 'low') vscode.window.showWarningMessage(`Preview risk: ${preview.risk_level}`); const panel = vscode.window.createWebviewPanel('bridgeAiPreview', 'AI Bridge Preview', vscode.ViewColumn.Beside, { enableFindWidget: true }); panel.webview.html = renderPreviewHtml(preview); }));
context.subscriptions.push(vscode.commands.registerCommand('bridgeAi.rejectChange', async (item) => { await withBridge(context, (bridge) => bridge.sessionDropChange(item.changeId), output); await refreshSession(); }));
context.subscriptions.push(vscode.commands.registerCommand('bridgeAi.rejectFile', async (item) => { await withBridge(context, (bridge) => bridge.sessionDropPath(item.filePath), output); await refreshSession(); }));
context.subscriptions.push(vscode.commands.registerCommand('bridgeAi.commitSession', async () => { const check = await withBridge(context, (bridge) => bridge.sessionPreview(), output); if (check.risk_level === 'high') { const answer = await vscode.window.showWarningMessage('Session preview is high risk. Commit anyway?', 'Commit', 'Cancel'); if (answer !== 'Commit') return; } const result = await withBridge(context, (bridge) => bridge.sessionCommit(), output); vscode.window.showInformationMessage(`AI Bridge committed ${result.committed_file_count} files`); await refreshSession(); }));
context.subscriptions.push(vscode.commands.registerCommand('bridgeAi.abortSession', async () => { const answer = await vscode.window.showWarningMessage('Abort current AI Bridge session?', 'Abort', 'Cancel'); if (answer !== 'Abort') return; await withBridge(context, (bridge) => bridge.sessionAbort(), output); await refreshSession(); }));
context.subscriptions.push(vscode.commands.registerCommand('bridgeAi.recoverSession', async () => { const bridge = await getBridge(context); const check = await bridge.recoveryCheck(); if (check.rebase_file_count > 0) { const answer = await vscode.window.showWarningMessage('AI Bridge session requires rebase. Rebase now?', 'Rebase', 'Cancel'); if (answer === 'Rebase') await bridge.recoveryRebase(); } await bridge.sessionRecover(); await refreshSession(); }));
const restoredSessionId = context.workspaceState.get('bridgeAi.sessionId'); if (restoredSessionId) refreshSession().catch(() => undefined); }
function deactivate() {}
module.exports = { activate, deactivate };
