param(
  [string]$BuildDir = "build",
  [string]$Config = "Release",
  [string]$ReportDir = ".windows_native_rerun",
  [int]$Jobs = 1
)
$ErrorActionPreference = 'Stop'
$RepoRoot = (Resolve-Path -LiteralPath '.').Path
$PowerShellExe = (Get-Command pwsh -ErrorAction SilentlyContinue)?.Source
if (-not $PowerShellExe) { $PowerShellExe = (Get-Command powershell).Source }
function Ensure-Dir([string]$Path) { New-Item -ItemType Directory -Force -Path $Path | Out-Null }
function Get-HostSummary { [ordered]@{ computer_name = $env:COMPUTERNAME; user_name = $env:USERNAME; os = [System.Environment]::OSVersion.VersionString; powershell = $PSVersionTable.PSVersion.ToString(); cmake = (& cmake --version | Select-Object -First 1); ctest = (& ctest --version | Select-Object -First 1) } }
Ensure-Dir $ReportDir
$summary = [ordered]@{ script = 'scripts/windows_native_rerun_record.ps1'; status = 'pending'; repo_root = $RepoRoot; build_dir = (Join-Path $RepoRoot $BuildDir); config = $Config; started_at = (Get-Date).ToUniversalTime().ToString('o'); finished_at = $null; host = Get-HostSummary; steps = @(); notes = @('This script is intended to be executed on a real Windows host.','Run after controlled-editing changes to refresh the native sign-off record.') }
function Run-Step([string]$Name, [scriptblock]$Action) { $start = Get-Date; try { & $Action; $end = Get-Date; $summary.steps += [ordered]@{ name = $Name; ok = $true; duration_ms = [math]::Round(($end - $start).TotalMilliseconds); message = 'ok' } } catch { $end = Get-Date; $summary.steps += [ordered]@{ name = $Name; ok = $false; duration_ms = [math]::Round(($end - $start).TotalMilliseconds); message = $_.Exception.Message }; throw } }
try { Run-Step 'build' { cmake --build $BuildDir --config $Config --parallel $Jobs }; Run-Step 'ctest-native-subset' { ctest --test-dir $BuildDir -C $Config --output-on-failure -R 'test_functional_windows_native|test_integration_windows_native|test_functional_windows_cli_contract|test_functional_windows_logging_codes|test_functional_windows_logging_success' }; Run-Step 'windows-smoke' { & $PowerShellExe -File ./scripts/windows_smoke.ps1 -BuildDir $BuildDir -Config $Config }; $summary.status = 'pass' } catch { $summary.status = 'fail' } finally { $summary.finished_at = (Get-Date).ToUniversalTime().ToString('o'); $jsonPath = Join-Path $ReportDir 'windows_native_rerun_record.json'; $mdPath = Join-Path $ReportDir 'windows_native_rerun_record.md'; $summary | ConvertTo-Json -Depth 8 | Set-Content -Path $jsonPath -Encoding utf8; $lines = [System.Collections.Generic.List[string]]::new(); $lines.Add('# Windows Native Rerun Record'); $lines.Add(''); $lines.Add("- Status: $($summary.status)"); $lines.Add("- Started (UTC): $($summary.started_at)"); $lines.Add("- Finished (UTC): $($summary.finished_at)"); $lines.Add(''); $lines.Add('## Host'); $lines.Add(''); foreach ($entry in $summary.host.GetEnumerator()) { $lines.Add("- $($entry.Key): $($entry.Value)") }; $lines.Add(''); $lines.Add('## Steps'); $lines.Add(''); foreach ($step in $summary.steps) { $status = if ($step.ok) { 'PASS' } else { 'FAIL' }; $lines.Add("- [$status] $($step.name) ($($step.duration_ms) ms): $($step.message)") }; $lines.Add(''); $lines.Add('## Notes'); $lines.Add(''); foreach ($note in $summary.notes) { $lines.Add("- $note") }; $lines -join "`r`n" | Set-Content -Path $mdPath -Encoding utf8; Write-Host "windows native rerun JSON: $jsonPath"; Write-Host "windows native rerun MD  : $mdPath"; if ($summary.status -ne 'pass') { exit 1 } }
